apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sqpystls0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sqpystls0-java-quarkus-gitops